<?php
/**
 * Copyright © 2019 Paazl. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Paazl\CheckoutWidget\Block\Checkout\Widget $block */
?>
<?php if ($block->getApiBaseUrl()) : ?>
<script type="text/javascript">window.PAAZL_CHECKOUT_WIDGET_API_URL = '<?php echo $block->getApiBaseUrl(); ?>';</script>
<?php endif; ?>
<?php if ($block->getCustomCss() != '') : ?>
<style>:root {<?php echo $block->getCustomCss() ?>}</style>
<?php endif; ?>
