<?php
/**
 * Copyright © 2019 Paazl. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Paazl\CheckoutWidget\Block\Checkout\Widget $block */
?>
<?php if ($block->getApiBaseUrl()) : ?>
<script type="text/javascript">
    window.PAAZL_CHECKOUT_WIDGET_API_URL = '<?= /* @escapeNotVerified */ $block->getApiBaseUrl(); ?>';
</script>
<?php endif; ?>
<?php if ($block->getCustomCss() != '') : ?>
<style>:root {<?= /* @escapeNotVerified */ $block->getCustomCss() ?>}</style>
<?php endif; ?>
