<?php
/**
 * Copyright © 2019 Paazl. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<?php
/** @var \Magento\Backend\Block\Template $block */
/** @var \Paazl\CheckoutWidget\ViewModel\Pickup\Info $viewModel */
$viewModel = $block->getData('pickupViewModel');
?>
<?php if ($pickupAddress = $viewModel->getPickupLocationAddressHtml()):?>
    <strong><?= $block->escapeHtml($viewModel->getPickupTitle()) ?></strong>
    <?= $block->escapeHtml($viewModel->getLocationName()) ?>
    <div class="pickup-info-wrapper">
        <?= /* @escapeNotVerified */ $pickupAddress ?>

        <?php if ($viewModel->getLocationCode()): ?>
            <div class="store-code-wrapper">
                <strong><?= /* @noEscape */ __('Pick-up location ID') ?>:</strong><br/>
                <?= $block->escapeHtml($viewModel->getLocationCode())?>
            </div>
        <?php endif; ?>
        <?php if ($description = $viewModel->getCarrierDescription()): ?>
            <div class="store-code-wrapper">
                <strong><?= /* @noEscape */ __('Carrier Description') ?>:</strong><br/>
                <?= $block->escapeHtml($description)?>
            </div>
        <?php endif; ?>
    </div>
<?php endif;?>

