<?php
/**
 * Copyright © 2019 Paazl. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div class="mm-block-paazl">
    <a class="helpbutton" href="<?php echo $block->escapeUrl($block->getSupportLink()); ?>" target="_blank">
        <?php echo __('Extension Manual'); ?>
    </a>
    <p>
        <strong><?php echo __('Paazl Checkout Widget.'); ?></strong><br>
        <?php echo __('We make shipping easy & fun.'); ?>
    </p>
</div>
