<?php
/**
 * Copyright © 2019 Paazl. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="mm-block-paazl">
    <a class="helpbutton" href="<?= /* @escapeNotVerified */ $block->escapeUrl($block->getSupportLink()); ?>" target="_blank">
        <?= /* @escapeNotVerified */ __('Extension Manual'); ?>
    </a>
    <p>
        <strong><?= /* @escapeNotVerified */ __('Paazl Checkout Widget.'); ?></strong><br>
        <?= /* @escapeNotVerified */ __('We make shipping easy & fun.'); ?>
    </p>
</div>
