<?php
/**
 * Copyright © 2019 Paazl. All rights reserved.
 * See COPYING.txt for license details.
 */


// @codingStandardsIgnoreFile

/* @var $block Paazl\CheckoutWidget\Block\Adminhtml\Order\Create\Shipping\Method\Paazl\Widget\Modal */
?>

<div id="paazl-modal" title="<?= $block->escapeHtml(__('Choose shipping method')) ?>"
     data-mage-init='<?= $block->escapeHtml($block->getPaazlWidgetModalJson()) ?>'>
    <div id="widget_paazlshipping_paazlshipping"></div>
</div>
